// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KernelUIClient is the client API for KernelUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KernelUIClient interface {
	// ListEngineSpecs returns a list of Virtualization Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (KernelUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type kernelUIClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelUIClient(cc grpc.ClientConnInterface) KernelUIClient {
	return &kernelUIClient{cc}
}

func (c *kernelUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (KernelUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &KernelUI_ServiceDesc.Streams[0], "/v1.KernelUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &kernelUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KernelUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type kernelUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *kernelUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kernelUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.KernelUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KernelUIServer is the server API for KernelUI service.
// All implementations must embed UnimplementedKernelUIServer
// for forward compatibility
type KernelUIServer interface {
	// ListEngineSpecs returns a list of Virtualization Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, KernelUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedKernelUIServer()
}

// UnimplementedKernelUIServer must be embedded to have forward compatible implementations.
type UnimplementedKernelUIServer struct {
}

func (UnimplementedKernelUIServer) ListEngineSpecs(*ListEngineSpecsRequest, KernelUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedKernelUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedKernelUIServer) mustEmbedUnimplementedKernelUIServer() {}

// UnsafeKernelUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelUIServer will
// result in compilation errors.
type UnsafeKernelUIServer interface {
	mustEmbedUnimplementedKernelUIServer()
}

func RegisterKernelUIServer(s grpc.ServiceRegistrar, srv KernelUIServer) {
	s.RegisterService(&KernelUI_ServiceDesc, srv)
}

func _KernelUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelUIServer).ListEngineSpecs(m, &kernelUIListEngineSpecsServer{stream})
}

type KernelUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type kernelUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *kernelUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _KernelUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.KernelUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KernelUI_ServiceDesc is the grpc.ServiceDesc for KernelUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KernelUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.KernelUI",
	HandlerType: (*KernelUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _KernelUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _KernelUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kernel-ui.proto",
}
